name: Sync Fork

on:
  schedule:
    # 00:00 UTC+7
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync with upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/Yamino-Kogetsu/GitHub_Stats/merge-upstream \
            -d '{"branch":"master"}'
